title: Menma JeM
author: Menmajem
email: menma.jem@gmail.com
description: >
  Um espaço dedicado à escrita.
  Aqui publico blogs, reflexões e histórias autorais.

theme: minima

markdown: kramdown

header_pages:
  - index.md
  - blogs.md
  - historias.md
  - sobre.md

minima:
  skin: dark

  plugins:
  - jekyll-feed
